name: Deploy Lambda to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adoptopenjdk'
        
    - name: Build with Maven
      run: mvn clean package

    - name: Deploy to AWS Lambda
      uses: einaregilsson/aws-lambda-deploy@v1
      with:
        function_name: fee-processor-faas
        zip_file: target/fee-processor-faas.zip
        region: eu-north-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-north-1
